apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: jira-messaging--runtime-ext
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # headless — StatefulSet pods resolve directly by DNS
